version: '3'
services:
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_starter
    container_name: go_starter_mysql
    ports:
      - "5000:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend
    restart: always
  web:
    build:
      context: ./web
    volumes:
      - "./web:/go/"
    container_name: go_starter_web
    environment:
      APP_NAME: go-starter
      UNIT_NAME: go-stater-web
      DEPLOY_ENV: production
      RES_MYSQL_GO_STARTER_MASTER_0_ADDR: root:root@mysql:3306/go_starter
      RES_MYSQL_GO_STARTER_SLAVE_0_ADDR: root:root@mysql:3306/go_starter
      SEQ_SERVER_ROOM_ID: 0
      SEQ_SERVER_NODE_ID: 0
    ports:
      - "8001:8001"
    tty: true
    depends_on:
      - mysql
    networks:
      - backend
    links:
      - "mysql:mysql"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "/apps/go-starter/bin/starter-web"]

networks:
  backend: